"""Investigator surface for the UI Fraud Coordination Agent.

A Streamlit-based web UI that lets state UI fraud investigators submit
natural-language investigation queries, see the agent's findings, and
review the audit trail.

Run with:
    uv run streamlit run src/ui/app.py
"""

from datetime import datetime, timezone
from typing import Optional
import re
import streamlit as st
import base64
# from dotenv import load_dotenv

# load_dotenv()

from src.agent.orchestrator import invoke_agent
from src.agent.tools.audit import list_audit_events


# ---------------- Page config ----------------
def _ensure_aware(dt):
    """Normalize a datetime to UTC-aware.

    MongoDB returns naive datetimes by default. Streamlit session state
    holds UTC-aware datetimes. This helper makes naive datetimes UTC-aware
    so comparisons work without raising TypeError.
    """
    if dt.tzinfo is None:
        return dt.replace(tzinfo=timezone.utc)
    return dt

st.set_page_config(
    page_title="UI Fraud Coordination Agent",
    page_icon="🔍",
    layout="wide",
)


# ---------------- Session state initialization ----------------

if "session_started_at" not in st.session_state:
    st.session_state.session_started_at = datetime.now(timezone.utc)

if "investigation_history" not in st.session_state:
    # List of dicts: {query, findings, error, started_at, completed_at, investigator_id}
    st.session_state.investigation_history = []

if "investigator_id" not in st.session_state:
    st.session_state.investigator_id = "demo_investigator"


# ---------------- Sidebar ----------------

with st.sidebar:
    

# Load and base64-encode the logo so we can inline it with custom styling

    with open("src/ui/assets/logo.png", "rb") as f:
        logo_b64 = base64.b64encode(f.read()).decode()

    st.markdown(
        f"""
        <div style="display: flex; flex-direction: column; align-items: center; margin-bottom: 1.5rem;">
            <img src="data:image/png;base64,{logo_b64}"
                style="width: 160px; height: auto; border-radius: 12px; margin-bottom: 0.75rem;"/>
            <h2 style="text-align: center; color: #2A2F2A; font-size: 1.2rem; margin: 0;
                    font-weight: 600; line-height: 1.3;">
                UI Fraud Investigative<br/>Agent
            </h2>
        </div>
        """,
        unsafe_allow_html=True,
    )

    st.divider()

    # Example queries first — they're the demo's guided tour
    st.markdown("**Try an example**")
    examples = [
        ("Cross-state SSN reuse", "Please investigate claim SA-000001126 for possible cross-state unemployment insurance fraud."),
        ("Within-state device collision", "Please investigate claim SA-000001174 for possible cross-state unemployment insurance fraud."),
        ("Clean claim (no matches)", "Please investigate claim SA-000000002 for possible cross-state unemployment insurance fraud."),
    ]
    for label, query in examples:
        if st.button(label, key=f"example_{label}", use_container_width=True):
            st.session_state.investigator_query = query
            st.rerun()

    st.divider()

    # Investigator identity — compact
    st.session_state.investigator_id = st.text_input(
        "Investigator identity",
        value=st.session_state.investigator_id,
        help="This identity appears in every audit log entry generated by your queries.",
    )

    st.divider()

    # Session info — compact, at the bottom
    st.caption(
        f"Session: started "
        f"{st.session_state.session_started_at.strftime('%H:%M UTC')} · "
        f"{len(st.session_state.investigation_history)} investigation(s)"
    )

# ---------------- Main content: tabs ----------------

tab_investigate, tab_audit = st.tabs(["Investigation", "Audit Log"])


# ---------------- Investigation tab ----------------

with tab_investigate:
    st.markdown(
        "The agent coordinates across State AA (legacy mainframe) and State BB (modern data store) under a privacy-preserving protocol with full audit trail."
    )
    st.caption("Powered by `gemini-2.5-flash` on Google Cloud Agent Platform.")

    st.divider()

    if "investigator_query" not in st.session_state:
        st.session_state.investigator_query = ""

    query = st.text_area(
        "Investigator query",
        height=100,
        placeholder=(
            "e.g., Please investigate claim SA-000001126 for possible "
            "cross-state unemployment insurance fraud."
        ),
        key="investigator_query",
    )
    st.caption(
                "💡 This agent investigates specific UI claims by claim ID "
                "(format `SA-NNNNNNNNN` or `SB-NNNNNNNNN`). "
                "Try one of the example queries in the sidebar to start."
            )
    submit_clicked = st.button(
        "Run investigation",
        type="primary",
        disabled=not query.strip(),
    )

    if submit_clicked and query.strip():
        started_at = datetime.now(timezone.utc)

        with st.spinner("Agent investigating — this may take 10-30 seconds..."):
            try:
                findings = invoke_agent(
                    user_query=query,
                    investigator_id=st.session_state.investigator_id,
                    verbose=False,
                )
                error: Optional[str] = None
            except Exception as e:
                findings = None
                error = f"{type(e).__name__}: {e}"

        completed_at = datetime.now(timezone.utc)

        st.session_state.investigation_history.append({
            "query": query,
            "findings": findings,
            "error": error,
            "started_at": started_at,
            "completed_at": completed_at,
            "investigator_id": st.session_state.investigator_id,
        })

    if st.session_state.investigation_history:
        st.divider()
        n = len(st.session_state.investigation_history)
        st.subheader(f"Findings · {n} {'investigation' if n == 1 else 'investigations'}")

        for i, item in enumerate(reversed(st.session_state.investigation_history)):
            claim_match = re.search(r"(SA-|SB-)\d+", item["query"])
            claim_ref = claim_match.group(0) if claim_match else "query"
            status = "⚠ error" if item["error"] else "✓ complete"
            duration = (item["completed_at"] - item["started_at"]).total_seconds()
            with st.expander(
                f"#{n - i} · {claim_ref} · {status} · "
                f"{item['started_at'].strftime('%H:%M:%S UTC')} · "
                f"{duration:.1f}s",
                expanded=(i == 0),
            ):
                st.caption(
                    f"**Investigator:** `{item['investigator_id']}` · "
                    f"**Query:** {item['query']}"
                )
                st.divider()

                if item["error"]:
                    st.error(f"Agent error: {item['error']}")
                elif item.get("findings") is not None:
                    findings = item["findings"]
                    st.markdown(findings.get("narrative", "_No narrative produced._"))

                    with st.expander("View structured findings (JSON)", expanded=False):
                        structured_only = {
                            k: v for k, v in findings.items() if k != "narrative"
                        }
                        st.json(structured_only)


# ---------------- Audit Log tab ----------------

with tab_audit:
    st.header("Audit Log")

    st.markdown(
        "Every cross-state federation query and quasi-identifier release "
        "writes a structured audit event. This log is the operational realization "
        "of 20 CFR 603's confidentiality requirements — every access is recorded "
        "with full provenance."
    )

    col_filter, col_refresh = st.columns([3, 1])
    with col_filter:
        scope = st.radio(
            "Scope",
            options=["This session only", "All events (recent 100)"],
            horizontal=True,
        )
    with col_refresh:
        st.write("")  # spacer for alignment
        refresh = st.button("🔄 Refresh", use_container_width=True)

    # Fetch events
    all_events = list_audit_events(limit=100)

    if scope == "This session only":
        events = [
            e for e in all_events
            if _ensure_aware(e["timestamp"]) >= st.session_state.session_started_at
        ]
    else:
        events = all_events

    st.caption(f"Showing {len(events)} event(s).")

    if not events:
        st.info(
            "No audit events to display. Run an investigation to populate the log."
        )
    else:
        # Display as a structured table
        for event in events:
            details = event.get("details", {})
            event_type = event["event_type"]

            # Color/icon by event type
            if event_type == "federation_query":
                icon = "🔍"
                title_suffix = (
                    f"hash match: A={details.get('matches_in_state_a', 0)}, "
                    f"B={details.get('matches_in_state_b', 0)}"
                )
            elif event_type == "quasi_identifier_release":
                icon = "🔓"
                title_suffix = f"claim {details.get('claim_id', '?')}"
            elif event_type == "quasi_identifier_release_failed":
                icon = "⚠️"
                title_suffix = f"FAILED: claim {details.get('claim_id', '?')}"
            else:
                icon = "📌"
                title_suffix = ""

            timestamp_str = event["timestamp"].strftime("%H:%M:%S UTC")

            with st.expander(
                f"{icon} {timestamp_str} | {event_type} | {title_suffix}",
                expanded=False,
            ):
                st.caption(f"**Investigator:** {event['requesting_investigator']}")
                st.caption(f"**Event hash:** `{event['event_hash']}`")
                st.json(details)

# ---------------- Footer ----------------


st.divider()
footer_left, footer_right = st.columns([3, 2])
with footer_left:
    st.caption(
        "Google Cloud Rapid Agent Hackathon · MongoDB Track · "
        "[GitHub repo](https://github.com/TaheraAhmed/ui-fraud-coordination-agent) · "
        "MIT licensed"
    )
with footer_right:
    st.caption(
        "Built with Gemini 2.5 Flash, MongoDB Atlas, "
        "Arize AX, and Dynatrace"
    )